---
# Source: kibana/templates/post-delete-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: post-delete-release-name-kibana
  labels: 
    app: kibana
    release: "release-name"
    heritage: Helm
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
subjects:
  - kind: ServiceAccount
    name: post-delete-release-name-kibana
    namespace: "default"
roleRef:
  kind: Role
  name: post-delete-release-name-kibana
  apiGroup: rbac.authorization.k8s.io
