---
# Source: fluentd/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-hddt
  labels:
    helm.sh/chart: fluentd-0.4.3
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.15.2"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-hddt
subjects:
  - kind: ServiceAccount
    name: fluentd-hddt
    namespace: efk
