---
# Source: fluentd/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-hddt
  labels:
    helm.sh/chart: fluentd-0.4.3
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.15.2"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentd
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        checksum/config: 518f3efed233aedd4c702f8ea8f9003239100025083dab37710a52f414f61714
      labels:
        app.kubernetes.io/name: fluentd
        app.kubernetes.io/instance: release-name
    spec:
      
      serviceAccountName: fluentd-hddt
      securityContext:
        {}
      containers:
        - name: fluentd
          securityContext:
            {}
          image: "fluent/fluentd-kubernetes-daemonset:v1.15.2-debian-elasticsearch7-1.0"
          imagePullPolicy: IfNotPresent
          env:
          - name: FLUENTD_CONF
            value: "../../../etc/fluent/fluent.conf"
          ports:
          - name: metrics
            containerPort: 24231
            protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          # readinessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          resources:
              {}
          volumeMounts:
          - name: etcfluentd-main
            mountPath: /etc/fluent
          - name: etcfluentd-config
            mountPath: /etc/fluent/config.d/
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      volumes:
      - name: etcfluentd-main
        configMap:
          name: fluentd-main-release-name
          defaultMode: 0777
      - name: etcfluentd-config
        configMap:
          name: fluentd-config-release-name
          defaultMode: 0777
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
