---
# Source: fluentd/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fluentd-hddt
  labels:
    helm.sh/chart: fluentd-0.4.3
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.15.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 24231
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: release-name
